title: Stackbit Agency Theme
baseurl: /
permalink: '/:title/'
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
sass:
  indentWidth: 4
  style: nested
  precision: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
cloudinary:
  cloud_name: okuma
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always