title: Stackbit Agency Theme
baseurl: /
permalink: '/:title/'
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
sass:
  indentWidth: 4
  style: nested
  precision: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
cloudinary:
  cloud_name: okuma
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always

comment-post: https://docs.google.com/forms/d/e/1FAIpQLSdttcxx5KG42Ub0yf_k0j9ZNMyygK66Mr0mQHy8bsi9e-uf8g
comment-post-fields: [ entry.1745873823, entry.1164485287, entry.913504291]
entry.1745873823: okuma-name
entry.1164485287: okuma-email
entry.913504291: okuma-message